run:
  max-same-issues: 0
  max-issues-per-linter: 0

issues:
  exclude:
    - Error return value of `.*\.EventErr(Kv)?` is not checked
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  goconst:
    min-occurrences: 2
  gocyclo:
    min-complexity: 32
  misspell:
    locale: US
  nakedret:
    max-func-lines: 0
  unparam:
    algo: cha
    check-exported: false

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    # - godox
    - gofmt
    # - gofumpt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
